import React from "react";
import { createRoot } from "react-dom/client";
import "@fontsource/dm-sans/latin-400.css";
import "@fontsource/dm-sans/latin-500.css";
import "@fontsource/dm-sans/latin-600.css";
import "@fontsource/lora/latin-400.css";
import "@fontsource/noto-sans-bengali/bengali-400.css";
import "@fontsource/noto-sans-arabic/arabic-400.css";
import "katex/dist/katex.min.css";
import "@folio/themes/document.css";
import "./style.css";
import { App } from "./App";
import { trackInitialPageView } from "./analytics";
trackInitialPageView();
createRoot(document.getElementById("root")!).render(<App />);
